pre-commit:
  parallel: true
  commands:
    block-sensitive-paths:
      run: |
        scripts/block-sensitive-paths.sh
    web-format:
      run: |
        pnpm --filter web format:check
    api-format:
      run: |
        cd apps/api && uv run black --check app tests
    worker-format:
      run: |
        cd apps/worker && uv run black --check app tests
