packages:
  - apps/*
  - packages/*
  - docs

overrides:
  next: 16.2.6
  postcss: 8.5.14
  rollup: 4.59.0

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
